# Generated by Django 3.2 on 2021-04-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('FIO', models.CharField(db_index=True, max_length=64, verbose_name='ФИО')),
                ('email', models.CharField(db_index=True, max_length=65, primary_key=True, serialize=False, verbose_name='email')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
