# Generated by Django 3.2 on 2021-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedan', '0002_auto_20210425_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_int', models.IntegerField()),
                ('test_int2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='data_stor',
            name='table_name',
            field=models.IntegerField(choices=[(1, 'Клиенты'), (2, 'Партнеры'), (3, 'Дистрибьюторы'), (4, 'Вендоры'), (5, 'Публичные домены'), (6, 'Отписавшиеся'), (7, 'Мусор')], verbose_name='Название таблицы'),
        ),
    ]
